# Generated by Django 5.0.7 on 2024-07-30 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0004_remove_order_f_status_id_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AccountManager'), (2, 'Customer'), (3, 'ServiceProvider')], default=1),
        ),
    ]
