# Generated by Django 5.0.7 on 2024-08-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0005_alter_accountmanager_user_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmanager',
            options={'verbose_name_plural': 'Account Managers list'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers list'},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'verbose_name_plural': 'Sevice Providers list'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': "PIC's Users"},
        ),
        migrations.CreateModel(
            name='JobStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_job_completion_time_per_job', models.FloatField()),
                ('number_of_jobs_per_status', models.FloatField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pic.report')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_services_used', models.IntegerField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Statistics',
                'db_table': 'UserStatistics',
            },
        ),
    ]
