# Generated by Django 5.0.7 on 2024-08-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0006_alter_accountmanager_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatistics',
            name='average_job_completion_time_per_job',
        ),
        migrations.AddField(
            model_name='jobstatistics',
            name='average_job_completion_time_per_job_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jobstatistics',
            name='number_of_jobs_per_status',
            field=models.JSONField(default=dict),
        ),
    ]
