# Generated by Django 5.0.7 on 2024-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0007_remove_jobstatistics_average_job_completion_time_per_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
