# Generated by Django 5.0.7 on 2024-08-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0008_serviceorder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCompletionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('regular', 'Regular'), ('wafer_run', 'Wafer Run')], max_length=20)),
                ('average_completion_time', models.FloatField(help_text='Average completion time in days.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic.report')),
            ],
            options={
                'unique_together': {('report', 'job_type')},
            },
        ),
        migrations.CreateModel(
            name='JobStatusCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed')], max_length=100)),
                ('count', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic.report')),
            ],
            options={
                'unique_together': {('report', 'status')},
            },
        ),
        migrations.DeleteModel(
            name='JobStatistics',
        ),
    ]
